mod-name: FarFutureTechnologies
package:
  include-dependencies: true  # Include dependencies in the package
  included-gamedata:
    - FarFutureTechnologies
  included-support:  # Include these root-level files in packages
    - readme.txt
    - changelog.txt
dependencies:  # Configure dependencies
  ModuleManager:
    version: 4.1.4
    location: s3
  B9PartSwitch:
    version: 2.17.0
    location: s3
  CommunityResourcePack:
    version: 1.4.2
    location: s3
  DynamicBatteryStorage:
    tag: 2.2.1
    location: github
    repository: post-kerbin-mining-corporation/DynamicBatteryStorage
  DeployableEngines:
    tag: 1.3.0
    location: github
    repository: post-kerbin-mining-corporation/DeployableEngines
  CryoTanks:
    tag: 1.6.0
    location: github
    repository: post-kerbin-mining-corporation/CryoTanks
  Waterfall:
    tag: 0.4.1
    location: github
    repository: post-kerbin-mining-corporation/Waterfall
  SystemHeat:
    tag: 0.3.7
    location: github
    repository: post-kerbin-mining-corporation/SystemHeat
  SpaceDust:
    tag: 0.3.3
    location: github
    repository: post-kerbin-mining-corporation/SpaceDust
deploy:
  SpaceDock:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 2603  # The Spacedock mod ID for deployment
  CurseForge:
    enabled: true  # activate/deactivate this deployment script
    mod-id: 432210  # The CurseForge mod ID for deployment
  GitHub:
    enabled: true  # activate/deactivate this deployment script
